
-- CLUSTERED INDEX
CREATE CLUSTERED INDEX [IXC_data_inclusao_partition] ON [dbo].[teste]
(
	[id] ASC,
	[data_inclusao] DESC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)
ON teste_data_inclusao_ps (data_inclusao)
GO


-- PK
ALTER TABLE [dbo].[teste]
ADD CONSTRAINT [PK_teste_id] PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)
ON [PRIMARY]
GO


-- NONCLUSTERED INDEX INSIDE THE PARTITION
CREATE NONCLUSTERED INDEX [IX_teste_index] ON [dbo].[teste]
(
	[field] ASC
)
INCLUDE([data_inclusao])
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)
ON teste_data_inclusao_ps (data_inclusao)
GO