# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sqlcheck:
    name: SQLCheck Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yokawasa/action-sqlcheck@v1.3.0
      id: sqlcheck
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        postfixes: sql
    - name: Get output
      run: echo "Issues found in previous step"
      if: steps.sqlcheck.outputs.issue-found
